DROP DATABASE riaw;

CREATE DATABASE riaw;

CREATE TABLE `riaw`.`t_human` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '记录创建时间',
  `mtime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '记录修改时间',
  `enabled` CHAR NOT NULL DEFAULT '1' COMMENT '生效状态（0：失效、1：生效）',
  `first_name` VARCHAR(45) NOT NULL COMMENT '姓氏',
  `last_name` VARCHAR(45) NOT NULL COMMENT '名字',
  `sex` CHAR NOT NULL COMMENT '性别（0：女、1：男）',
  `birthday` DATE NULL COMMENT '生日',
  PRIMARY KEY (`id`))
COMMENT = '系统人员表';

CREATE TABLE `riaw`.`t_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '记录创建时间',
  `mtime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '记录修改时间',
  `enabled` CHAR NOT NULL DEFAULT '1' COMMENT '生效状态（0：失效、1：生效）',
  `human_id` INT UNSIGNED NOT NULL COMMENT '系统人员ID',
  `user_name` VARCHAR(45) NOT NULL COMMENT '用户名',
  `password` VARCHAR(45) NOT NULL COMMENT '密码',
  PRIMARY KEY (`id`))
COMMENT = '系统用户表';

CREATE TABLE `riaw`.`t_measurement_unit` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '记录创建时间',
  `mtime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '记录修改时间',
  `unit_name` VARCHAR(45) NOT NULL COMMENT '单位名称',
  PRIMARY KEY (`id`))
COMMENT = '计量单位表';

CREATE TABLE `riaw`.`t_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '记录创建时间',
  `mtime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '记录修改时间',
  `enabled` CHAR NOT NULL DEFAULT '1' COMMENT '生效状态（0：失效、1：生效）',
  `product_name` VARCHAR(45) NOT NULL COMMENT '产品名称',
  PRIMARY KEY (`id`))
COMMENT = '产品表';

CREATE TABLE `riaw`.`t_product_pricing` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '记录创建时间',
  `mtime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '记录修改时间',
  `product_id` INT UNSIGNED NOT NULL COMMENT '产品ID',
  `unit_id` INT UNSIGNED NOT NULL COMMENT '计量单位ID',
  `unit_price` DOUBLE(10, 2) UNSIGNED NOT NULL COMMENT '单价',
  PRIMARY KEY (`id`))
COMMENT = '产品定价表';

CREATE TABLE `riaw`.`t_menu` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '记录创建时间',
  `mtime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '记录修改时间',
  `mid` VARCHAR(45) NOT NULL COMMENT '菜单ID',
  `text` VARCHAR(45) NOT NULL COMMENT '菜单名',
  `p_mid` VARCHAR(45) NOT NULL COMMENT '父菜单ID',
  `url` VARCHAR(45) NULL COMMENT '链接地址',
  `leaf` CHAR NOT NULL COMMENT '叶子节点（0：否、1：是）',
  PRIMARY KEY (`id`))
COMMENT = '系统菜单表';

CREATE TABLE `riaw`.`t_user_menu` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '记录创建时间',
  `mtime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '记录修改时间',
  `user_id` INT UNSIGNED NOT NULL COMMENT '系统用户ID',
  `menu_id` INT UNSIGNED NOT NULL COMMENT '系统菜单ID',
  PRIMARY KEY (`id`))
COMMENT = '用户菜单表';

CREATE TABLE `riaw`.`t_delivery_note` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '记录创建时间',
  `mtime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '记录修改时间',
  `record_no` VARCHAR(45) NOT NULL COMMENT '备案号',
  `customer` VARCHAR(45) NOT NULL COMMENT '购货单位',
  `delivery_van` VARCHAR(45) NOT NULL COMMENT '送货车号',
  `delivery_date` DATE NOT NULL COMMENT '送货日期',
  `order_no` VARCHAR(45) NOT NULL COMMENT '订单编号',
  `delivery_man` VARCHAR(45) NOT NULL COMMENT '送货员',
  `container_deliver` INT UNSIGNED NULL COMMENT '配送周转箱数',
  `container_take` INT UNSIGNED NULL COMMENT '接收周转箱数',
  `enabled` CHAR NOT NULL DEFAULT '1' COMMENT '生效状态（0：失效、1：生效）',
  PRIMARY KEY (`id`))
COMMENT = '送货单表';

CREATE TABLE `riaw`.`t_delivery_note_detail` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ctime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '记录创建时间',
  `mtime` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '记录修改时间',
  `delivery_note_id` INT UNSIGNED NOT NULL COMMENT '送货单ID',
  `product_pricing_id` INT UNSIGNED NOT NULL COMMENT '产品价目ID',
  `quantity` INT UNSIGNED NOT NULL COMMENT '产品数量',
  `amount` DOUBLE(10, 2) UNSIGNED NOT NULL COMMENT '单项金额',
  `production_date` DATE NOT NULL COMMENT '生产日期',
  `comments` VARCHAR(1000) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
COMMENT = '送货单明细表';